"""initial migration

Revision ID: 464a6b8665a8
Revises: f5718af5ec36
Create Date: 2016-01-21 11:23:40.851150

"""

# revision identifiers, used by Alembic.
revision = '464a6b8665a8'
down_revision = 'f5718af5ec36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
