"""initial migration

Revision ID: 5102d49377c5
Revises: 9504559f709b
Create Date: 2016-01-12 15:56:37.002492

"""

# revision identifiers, used by Alembic.
revision = '5102d49377c5'
down_revision = '9504559f709b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
